version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Logging in to DockerHub...
      - echo $Yogesh@123 | docker login -u $cheemslaika --password-stdin
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $cheemslaika/brain-app:latest .
  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $cheemslaika/brain-app:latest
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region ap-south-1 --name brain-cluster
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
